version: "3.4"

services:
  ticketsvc:
    image: matspinner/ticketsvc
    build:
      context: ./
      dockerfile: ./ticketsvc/Dockerfile
    ports:
      - 8085:8085
  spinsvc:
    image: matspinner/spinsvc
    build:
      context: ./
      dockerfile: ./spinsvc/Dockerfile
    ports:
      - 8086:8086
  playersvc:
    image: matspinner/playersvc
    build:
      context: ./
      dockerfile: ./playersvc/Dockerfile
    ports:
      - 8087:8087
