version: "3.4"

services:
  ticketsvc:
    image: matspinner/ticketsvc
    build:
      context: ./ticketsvc
      dockerfile: ./Dockerfile
    ports:
      - 8085:8085
  spinsvc:
    image: matspinner/spinsvc
    build:
      context: ./spinsvc
      dockerfile: ./Dockerfile
    ports:
      - 8086:8086
